language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    rooms:
      secure: u/1ZjPtdqs1HlSgdG13WX3I+2yYiL2UbU3nq/Fhbbc9R+PxiHHhVcSbbsIvGm9YEeXVIxmsCRfVd6NJwWWhYameDRqkxtcvom5bbFv9F/o/YfuwMW0nz5JGnXVfotP0wFdzVza2Cl+Sf5fbTL0aiQzluaBh+tKgkLFGJQ/Br5ydnf7D3RyS3U6HxSPBFNLgb1esu09ecncvOu0JAY6hThxYOufC4gJLMLZhrfN9t6ot52lHsKd9KYGyL5nVczRPky18d02/Z+yiwLZ0zH4NAGsdctwigIbtFY42OltCGHuHuWDuV8ufXdxPPJWbnQqCDLPJIGz1twarxpfPBvfE0Rf9XdGiF4PDmASH9dB24fI6sGvd86e56jx36abnmI1yYMK803xbsKDE1GdQiisUNwDpxK1HYJuZaPgsoypkV1qf0nch9/9GHD88L4NYCiWfGnPPC13Ae+p/DiqfNw2H/jKbLL9JadZRzhqG+s2wySsJ8Gje56Wh5vkrPKxHO0LNGv+2J8LleAzs+BPN2edmXLkVcdAbLVX2BrVjRFwlo/6r/wiCMWQYpLRq5+smpp2898vDK0iDz/HcZemCzOin3OyOQiDRqaYJGNJ0MZ6HV8csZ10qbnjn/Hsmw+X/MX3LPiuSYuCzin6+kiwh08tQDJNMbxlRWuFf+HMOUAC+z8Qc=
deploy:
  provider: heroku
  api_key:
    secure: fKCkDCOefjpH9jxFkKhzv3eyjNKV/CXndPwjYKaHeofoDZ7bvvAF0IkT5oSPjLGihyeUyR+zXLT0TioC0tD3pndSL78/ZJZD7riiSV9NKH2U+6CY8L772fUI/alOVKJpfnNm+kTMHOWoydhcPDrqwrFqfuLJENMFl6xzHrF5aTUBAm7Y8bOOBcUBDLR6cv+oTHlUbHlpa/RBT/BCt2t1LgT00MB+xahAu62NDK4JEi/YrMij+UQctwl8AkyVOjodFRisi5yi3nLIq6CHImrcvR9HBCL+21hGhb5VM3uCaQ3kgFkfoVIaCUMQ98jtdLfJbl6rYwOifavd2SRZE3rQAdRfvL1lTuOv5AoEx9EXaFhBPAssTV0ZXNeqll8S8lhaKM2fKTP4daw8S1Aj1nea509YGzDpc1o/JKLtqJBCcw4eQ8weNfn3YbWysRolmcZvcqbtaGtljQienIAylirFQ9lNOHPgUlUA46fXOeZ0cpjl2J1rkSb1GJDGymw42RRLtvgI6DHKKKBNMovjoEo5GEMcRs3T3SVW2l2oOyfdkVQWYb+iXk95VOpMTPKg27BtcASc/bqKkNVckB3Ek91t+Fyz8Y1/GLsPeG3q/qz423NMpxRuGMU0+bAPBMIXItNIjJiKuGd7QR/Riq1OVOBzpcS7QZ4Lfw5F0Z/yGeknVgk=
  app: cozyan