language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    rooms:
      secure: Ar/tRSoiTJCBYCTLXWM7hQJYp+JnK5IZ2NiBn90byEzQBmsfgienm2gckn0iz8+g8DskOuO0rHaTwmef6vLfAVn1iJ8Rq4w2L57W+iN5poyucjf9kzXXfurWWqCwmZ0Y8bGQm4QMfL95qgGIIcgBHJv3z0N1DbvlLk3BeUm3MFpdFI4wfznN5BykimV5vk5fMD4CN5VqNkYtdFtQ/HWjXmjQ7cKSZlxrnllP2C0fn+rB89qoV3J6mK/voVInQbJgchm/OSjeLd9/qnMVJYSo4+uKI/vRBzK8GcxzNTAkKU1FcNYZWBTm0HSBgK9me8Kfp3jehhSK2rIy6VD5jteyo2WQT8pqf655ccQWuQGnRUSfeIDL+bBXlwvXlHel+z7HlHvAekl97AKUw5SWk40KiA7peq7HRaX45Dh2jdNVI3WdvrHPhtcC51jNsWcSUa/bRE+fWtceiQ/I4ClYipTfTJjsRuTnVcPkoz+CQ6dF2f7qDDAMVGC7qQVdD1k5BEWBOQs/AjTXKx17DRkhgXHFB+kT7+1JldlYqjyqlHk/79EyUeHpTkhKppP2kwj+/94LeQSHOAHK8ogSNK9gGWVwL1Rng2Kq2DZizKdxDx+GXaMrjgRkCCCxY0v7CEUEVH1uJM/V/AuCSFC4yy76S1deC5bXWiySd+8FjtSuHHzh8wY=
