language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    rooms:
      secure: u/1ZjPtdqs1HlSgdG13WX3I+2yYiL2UbU3nq/Fhbbc9R+PxiHHhVcSbbsIvGm9YEeXVIxmsCRfVd6NJwWWhYameDRqkxtcvom5bbFv9F/o/YfuwMW0nz5JGnXVfotP0wFdzVza2Cl+Sf5fbTL0aiQzluaBh+tKgkLFGJQ/Br5ydnf7D3RyS3U6HxSPBFNLgb1esu09ecncvOu0JAY6hThxYOufC4gJLMLZhrfN9t6ot52lHsKd9KYGyL5nVczRPky18d02/Z+yiwLZ0zH4NAGsdctwigIbtFY42OltCGHuHuWDuV8ufXdxPPJWbnQqCDLPJIGz1twarxpfPBvfE0Rf9XdGiF4PDmASH9dB24fI6sGvd86e56jx36abnmI1yYMK803xbsKDE1GdQiisUNwDpxK1HYJuZaPgsoypkV1qf0nch9/9GHD88L4NYCiWfGnPPC13Ae+p/DiqfNw2H/jKbLL9JadZRzhqG+s2wySsJ8Gje56Wh5vkrPKxHO0LNGv+2J8LleAzs+BPN2edmXLkVcdAbLVX2BrVjRFwlo/6r/wiCMWQYpLRq5+smpp2898vDK0iDz/HcZemCzOin3OyOQiDRqaYJGNJ0MZ6HV8csZ10qbnjn/Hsmw+X/MX3LPiuSYuCzin6+kiwh08tQDJNMbxlRWuFf+HMOUAC+z8Qc=
deploy:
  provider: heroku
  api_key:
    secure: mkhKZG610sbyb4V6opmHsWGvlpdmkqYHNGIftzytu8tpr34u5xXKOH1TvuyNIcy1+smhucLSKSi6NIo2bgjhzRUGUnjMrWn2VjslPEZGXNmD7jjIyALg5qlbxdQlr1mZDuCwBHm/Z+P94pf0xJtTuPB6nNkLfoAP3O1naC77xKnp1XTgGC6Sn7XfyqM1aIkXErISfmK8oiJK2SvZGI131schAyPeHQYzxJlA+N+v5n8xho8Y3eGAfxqIet5g9ZLasVIfnVG2A0KmUltSacmkRBZjF3HLJBZpHS65sYajJWcDZYdQl6cbR4E1mXdeO668QzLwbNwqrM97BOiJD4Cr2CXX/QZRu98GFGaNCv7VD3wArUBDLDuzaBdF/AtQIUmanMpIYfAlnYnNx1qTd5nNRh1b1sXG2fkUuiiF03xlvTo3LSXKZ7Z6vzPjerx+p/pCjWTPBVDY93UvwBaxwMJmzmUgYHpJWJoCscuTs5UEzCHT4PDztUqVEJuPoNnXWGxYMZa57flUCy7+iUjyP0p4g6cnoauNdfw7JjtQlR+WQ+yY7rzxOAGdWod+g2aeblpd3NPzOYq/A61LWUCPf2IsmUmlDe/97WNuovqSvvVZBEf+l0qjjh3h8dNd4bXi0NCdS3ONmkFhoIj1Aczn3Y/GgtoDhbqAsFcjKitVnQ04434=
  app: cozyan
